package storage

import (
	"gorm.io/gorm"
	"os"

	"github.com/osscameroon/jobsika/pkg/models/v1beta"
)

// GetJobTitles get jobtitles
func (db DB) GetJobTitles() ([]string, error) {
	var titles []string
	jobTitles := []v1beta.JobTitle{}

	//Check if the last jobTitle already exists
	defaultJobTitle := v1beta.JobTitle{}
	ret := db.c.Table("jobtitles").Where("title = ?", DefaultJobTitles[len(DefaultJobTitles)-1]).Find(&defaultJobTitle)
	if ret.Error != nil {
		return titles, ret.Error
	}

	//If we did not find the last jobTitle, we create every jobTitles
	if defaultJobTitle.Title == "" {
		tmpJobTitles := DefaultJobTitles
		//If we are running tests we use a short list of jobtitles
		if os.Getenv("ENVIRONMENT") == "test" {
			tmpJobTitles = []string{"Tester"}
		}

		for _, j := range tmpJobTitles {
			tmpTitle := v1beta.JobTitle{}

			//I the jobtitle exists we don't create it
			ret := db.c.Table("jobtitles").Where("title = ?", j).Find(&tmpTitle)
			if tmpTitle.Title != "" || ret.Error != nil {
				continue
			}

			jobTitle := v1beta.JobTitle{
				Title: j,
			}

			db.c.Table("jobtitles").Create(&jobTitle)
		}
	}

	//Get the list of jobTitles again
	ret = db.c.Table("jobtitles").Order("title").Find(&jobTitles)
	if ret.Error != nil {
		return titles, ret.Error
	}

	for _, t := range jobTitles {
		titles = append(titles, t.Title)
	}

	return titles, nil
}

func postJobTitle(tx *gorm.DB, title string) (v1beta.JobTitle, error) {
	jobTitle := v1beta.JobTitle{}

	//Check if the jobTitle already exist
	ret := tx.Table("jobtitles").Where("title = ?", title).Find(&jobTitle)
	if ret.Error != nil {
		return jobTitle, ret.Error
	}

	if jobTitle.Title == "" {
		//if we did not find the jobTitle, we create a new jobTitle entry
		jobTitle = v1beta.JobTitle{
			Title: title,
		}
		ret := tx.Table("jobtitles").Create(&jobTitle)
		if ret.Error != nil {
			return jobTitle, ret.Error
		}
	}

	return jobTitle, nil
}

// DefaultJobTitles is collection of default jobtitles
var DefaultJobTitles = []string{
	"2D Animator",
	"3D Animator",
	"3D Director",
	"3D Measurement Technician",
	"ABAP Developer",
	"ACCESS Developer",
	"AGILE Consultant",
	"ANDROID Developer",
	"APPLE Developer",
	"AS3 Developer",
	"ASP Developer",
	"Accessibility Consultant",
	"Accommodation Manager",
	"Accompanist",
	"Account Manager",
	"Accountant",
	"Accountant Accounts receivable Accounts payable",
	"Accountant Clients",
	"Accountant Supplier",
	"Accountant Treasury",
	"Accounting Assistant",
	"Accounting Auditor",
	"Accounting Consultant",
	"Accounting Executive",
	"Accounting Manager",
	"Accounting Secretary",
	"Accounting Technician",
	"Accounting and Administrative Manager...",
	"Accounting and Management Technician",
	"Accounting and Payroll Consultant",
	"Accounting assistant",
	"Accounts Payable Manager...",
	"Accounts Receivable Collection",
	"Accounts Receivable Manager",
	"Acoustic Technician",
	"Actuarial Consultant Compensation and...",
	"Actuarial and Risk Consultant...",
	"Actuary",
	"Actuary Consultant",
	"Actuary Underwriting",
	"Adjuster",
	"Administrative Assistant",
	"Administrative Attaché",
	"Administrative Consultant",
	"Administrative Director",
	"Administrative Employee",
	"Administrative Manager",
	"Administrative Officer",
	"Administrative Secretary",
	"Administrative and Accounting Manager...",
	"Administrative and Financial Assistant",
	"Administrative and Financial Director",
	"Administrative and Financial Manager...",
	"Advertising Space Salesperson",
	"Advisor in Socio-Anthropology",
	"Advocacy Advisor",
	"Aeronautical Assembler",
	"Aeronautical Cable Maker",
	"Aeronautical Cabling Operator",
	"Aeronautical Fitter",
	"Aeronautical Maintenance Technician",
	"Aeronautical Mechanic",
	"Aeronautical Numerical Control Operator...",
	"Aeronautical Pipefitter",
	"Aeronautical Technician",
	"Aeronautical fitter",
	"Aeronautical painter",
	"Aerostructure Technician",
	"After Sales Service Agent",
	"After Sales Service Manager",
	"Agency Manager",
	"Agent Help Desk",
	"Agent Information",
	"Agent Inside Sales",
	"Agent Mailer",
	"Agri-food technician",
	"Agri-food worker",
	"Agricultural Advisor",
	"Agricultural Equipment Salesman",
	"Agricultural Machinery Mechanic",
	"Agricultural Technical Officer",
	"Agricultural Technician",
	"Agricultural Worker",
	"Agricultural mechanic",
	"Agronomist",
	"Aid and Subsidy Consultant",
	"Air Conditioning Design Technician",
	"Air Conditioning Maintenance Technician",
	"Air Conditioning Technician",
	"Air Operations Officer",
	"Aircraft Maintenance Technician",
	"Aircraft Mechanic",
	"Airport Ramp Agent",
	"Airport Security Officer",
	"Aluminium Technician",
	"Aluminium carpenter",
	"Ambulance driver",
	"Anaesthesiologist Resuscitator",
	"Anaesthetist Nurse",
	"Analyst",
	"Analyst Designer",
	"Analyst Developer",
	"Analyst Director",
	"Analyst Programmer",
	"Analytical Laboratory Technician",
	"Animal Caretaker",
	"Animal Salesman",
	"Animator",
	"Antenna technician",
	"Application Architect",
	"Application Developer",
	"Application Integrator",
	"Application Manager",
	"Application Security Coordinator",
	"Application Support",
	"Application Support Agent",
	"Application Tester",
	"Aquaculture and Fisheries Management Consultant...",
	"Aquaculturist",
	"Arc welder",
	"Architect",
	"Architect Technical Auditor",
	"Architectural Technician",
	"Archiving Agent",
	"Archivist",
	"Area Manager",
	"Area Sales Manager",
	"Art Director",
	"Art Therapist",
	"Art teacher",
	"Artisan",
	"Artist Painter",
	"Assembler Welder",
	"Assembly Agent",
	"Assembly Technician",
	"Asset Management Advisor",
	"Asset Manager",
	"Assistant",
	"Assistant Accountant",
	"Assistant Management Controller",
	"Assistant Project Manager",
	"Assistant Site Manager",
	"Assistant Store Manager",
	"Associate Architect",
	"Associate Lawyer",
	"Audioprosthesist",
	"Audiovisual Manager",
	"Audiovisual Production Manager",
	"Audiovisual Technician",
	"Audiovisual cameraman",
	"Audit and Management Control Consultant...",
	"Audit and Management Systems Consultant...",
	"Auditor",
	"Auditor Consultant",
	"Automated Line Operator",
	"Automatic Machine Operator in the...",
	"Automation Maintenance Technician",
	"Automation Technician",
	"Automotive Diagnostic Technician",
	"Automotive Electrician",
	"Automotive Expert",
	"Automotive Maintenance Technician",
	"Automotive Manufacturing Agent",
	"Automotive Receptionist",
	"Automotive Sales Advisor",
	"Automotive Sales Manager",
	"Automotive Service Mechanic",
	"Automotive Technical Assessor",
	"Automotive Technical Support Officer...",
	"Automotive Technician",
	"Auxiliary of Life",
	"Auxiliary of Social Life",
	"Aviation Security Consultant",
	"B to B Sales",
	"B to B Sales Technician",
	"B to C Sales",
	"B to C Sales Technician",
	"BPO Sourcing Officer",
	"Back-Office Assistant",
	"Back-Office Manager",
	"Baggage handler",
	"Baker",
	"Baker and confectioner",
	"Bakery Preparer Salesperson",
	"Bakery and pastry seller",
	"Bank Branch Manager",
	"Bank employee",
	"Bank teller",
	"Banking Consultant",
	"Barista",
	"Barman",
	"Beautician",
	"Beauty Centre Manager",
	"Beauty and Cosmetics Salesman...",
	"Behaviourist Doctor",
	"Beta Tester",
	"Bilingual Assistant",
	"Bilingual Secretary",
	"Billing Agent",
	"Billing Assistant",
	"Billing Manager",
	"Bio Computer Scientist",
	"Biochemical Technician",
	"Biochemist",
	"Biological Technician",
	"Biologist",
	"Biomedical Analysis Technician",
	"Biomedical Maintenance Technician",
	"Biomedical Technician",
	"Biostatistician",
	"Boatman",
	"Body Repairer",
	"Body Shop Manager",
	"Body painter",
	"Bodybuilder",
	"Bodyguard",
	"Bodywork Development Technician...",
	"Boiler Operator",
	"Boilermaker Aerospace",
	"Boilermaker Sheet Metal Worker",
	"Boilermaker Technician",
	"Book seller",
	"Bookbinder Gilder",
	"Booking Agent",
	"Bookstore employee",
	"Bookstore salesperson",
	"Boutique Manager",
	"Branch Manager",
	"Brand Ambassador",
	"Brand Manager",
	"Breeder",
	"Brodeur",
	"Broker",
	"Building Design Technician",
	"Building Electrician",
	"Building Maintenance Manager",
	"Building Maintenance Officer",
	"Building Sales Technician",
	"Building labourer",
	"Building painter",
	"Building technician",
	"Building worker",
	"Bus Driver",
	"Bus driver",
	"Business Analyst",
	"Business Consultant",
	"Business Contributor",
	"Business Creation Advisor",
	"Business Customer Advisor",
	"Business Developer",
	"Business Development Consultant...",
	"Business Development Manager",
	"Business Intelligence Architect",
	"Business Intelligence Consultant and...",
	"Business Intelligence Developer",
	"Business Intelligence Expert",
	"Business Intelligence Manager",
	"Business Lawyer",
	"Business Management Consultant...",
	"Business Manager",
	"Business Modelling Consultant",
	"Business Planner",
	"Business Transformation Consultant",
	"Business Unit Director",
	"Business Unit Manager",
	"Business and Management Consultant",
	"Butcher Charcutier",
	"Buyer",
	"Buyer Advertising Space",
	"C Developer",
	"CAD Technician",
	"CAD technician",
	"COBOL Developer",
	"CRM Consultant",
	"CRM Project Manager",
	"CRM Salesforce Manager",
	"CRM Strategy Consultant",
	"Cabinetmaker",
	"Cable Fitter",
	"Cable installer",
	"Cabling Operator",
	"Call Center Agent",
	"Call Centre Operator",
	"Call Centre Supervisor",
	"Call centre",
	"Calligrapher",
	"Cambist",
	"Camera Operator",
	"Camera Technician Editor",
	"Cameraman",
	"Capability Manager",
	"Capital Markets Consultant",
	"Captain of Maritime Navigation",
	"Captain of the Merchant Navy",
	"Car Preparer",
	"Car mechanic",
	"Car painter",
	"Cardiologist",
	"Caretaker",
	"Carpenter",
	"Carpenter Cabinetmaker",
	"Carpenter Fitter",
	"Carpenter Workshop",
	"Carpenter's helper",
	"Carpentry Technician",
	"Carpentry fitter",
	"Cartoonist",
	"Cash Collection Manager",
	"Cash Manager",
	"Cashier",
	"Cashier Supervisor",
	"Cashier's assistant",
	"Category Management Consultant",
	"Category Manager",
	"Catenary Technician",
	"Catering Agent",
	"Catering Manager",
	"Catering cook",
	"Catering employee",
	"Census Officer",
	"Ceramicist",
	"Chambermaid",
	"Change Management Consultant",
	"Change Management Consultant...",
	"Change Manager",
	"Character Designer",
	"Chargé de Missions Humanitaires",
	"Chartered Accountant",
	"Cheese maker",
	"Chef Garde Manger",
	"Chef de Cuisine",
	"Chef de Partie",
	"Chemical Laboratory Technician",
	"Chemical Manufacturing Technician",
	"Chemical Quality Control Technician",
	"Chemical Technician",
	"Chemist",
	"Chief Accountant",
	"Chief Architect",
	"Chief Editor",
	"Chief Engineer",
	"Chief Executive Officer",
	"Chief Operator",
	"Chief Steward",
	"Childcare assistant",
	"Childminder",
	"Children's entertainer",
	"Chiropodist",
	"Chocolatier",
	"Chocolatier Confiseur",
	"Choreographer",
	"Cinema Director",
	"Civil Engineering Inspector",
	"Civil Engineering Technician",
	"Claims Agent",
	"Claims Manager",
	"Claims Writer",
	"Claims adjuster",
	"Clavist",
	"Cleaning Team Leader",
	"Cleanliness and Hygiene Officer",
	"Clerk",
	"Clerk of the rank",
	"Client Portfolio Manager",
	"Clinic Director",
	"Clinical Psychologist",
	"Clinical Research Associate",
	"Clinical Studies Coordinator",
	"Clothing Methods Officer",
	"Clown",
	"Club Manager",
	"Co-ownership Accountant",
	"Co-ownership Manager",
	"Co-ownership agent",
	"Coach",
	"Coffee boy",
	"Collection Agent",
	"Collection Manager",
	"Collection Officer",
	"Collective Accompaniment Consultant",
	"Collective Intelligence Consultant...",
	"Columnist",
	"Comedian",
	"Commercial Agent",
	"Commercial Attaché",
	"Commercial Director",
	"Commercial Inspector",
	"Commercial Insurance",
	"Commercial Manager",
	"Commercial Real Estate",
	"Commercial Sales",
	"Commercial Secretary",
	"Commercial Showroom",
	"Commercial Spare Parts and Accessories...",
	"Commercial Supervisor",
	"Communication Assistant",
	"Communication Consultant",
	"Communication Director",
	"Communication Manager",
	"Communication Officer",
	"Community Manager",
	"Community Services Officer and...",
	"Company driver",
	"Compensation and Benefits Consultant...",
	"Complaints Officer",
	"Compliance Officer",
	"Compliance and Internal Control Manager...",
	"Composer",
	"Composite Materials Technician",
	"Compressor Technician",
	"Computer Developer",
	"Computer trainer",
	"Concierge Hotel",
	"Concrete Aggregates Laboratory Technician...",
	"Concrete Plant Operator",
	"Confectioner",
	"Configuration Manager",
	"Confirmor",
	"Consolidation Officer",
	"Consolidation and IFRS Consultant",
	"Consolidator",
	"Construction Cost Manager",
	"Construction Equipment Mechanic",
	"Construction Equipment Operator",
	"Construction Fluid Technician...",
	"Construction Manager",
	"Construction Site Manager",
	"Construction Team Leader",
	"Consultant",
	"Consultant Advisory Insurance",
	"Consultant Assesment",
	"Consultant Credit Risk Analyst",
	"Consultant Organisation Strategy",
	"Consultant Organisation and Management of...",
	"Consultant Pharmaceutical Sector",
	"Consultant Project Manager",
	"Consultant Psychologist",
	"Consultant Sociologist",
	"Consultant Sponsored Links",
	"Consultant Strategy Customer and...",
	"Consultant Trainer",
	"Consultant Transaction Services",
	"Consultant in Accounting Support for...",
	"Consultant in Business Development...",
	"Consultant in Business Organisation...",
	"Consultant in Economic and Financial Diagnosis...",
	"Consultant in Land Law",
	"Consultant in Occupational Psychology",
	"Consultant in Organisation and Methodology...",
	"Consultant in Policy Evaluation...",
	"Consultant in Psychosocial Risks",
	"Consultant in Risk Management and...",
	"Consultant in Social Controlling...",
	"Consultant in Socio-Anthropology",
	"Consultant in Strategy and Business Development...",
	"Consulting",
	"Consulting and Expertise",
	"Content Planner",
	"Content Writer",
	"Content Writing Consultant",
	"Contract Finance Consultant",
	"Contract Manager",
	"Contract Room Manager",
	"Control Officer",
	"Controller",
	"Controller General",
	"Cook",
	"Cook's helper",
	"Cooperative Enterprise Advisor...",
	"Coordinator",
	"Coordinator Association",
	"Corporate Finance Consultant",
	"Corporate lawyer",
	"Corrector",
	"Cosmetics Sales Representative",
	"Costing Technician",
	"Costume designer",
	"Counter Agent",
	"Counter Manager",
	"Counter salesperson",
	"Country Manager",
	"Courier",
	"Couturier",
	"Crane Operator",
	"Crane operator",
	"Credit Analyst",
	"Credit Management Consultant",
	"Credit Manager",
	"Crepe maker",
	"Crimper",
	"Cross-functional Project Manager",
	"Cultivator",
	"Culture and Heritage Project Manager",
	"Curator of Archaeology",
	"Customer Advisor",
	"Customer Consultant",
	"Customer Marketing Consultant",
	"Customer Relationship Consultant",
	"Customer Relationship Manager",
	"Customer Service Agent",
	"Customer Service Manager",
	"Customer Service Officer",
	"Customs Declaring Agent",
	"Customs declarant",
	"Cutter",
	"Cutter Clothing",
	"Cutting Operator",
	"DTP Operator",
	"Dairy Production Worker",
	"Dairy technician",
	"Dance teacher",
	"Data Entry Operator",
	"Database Administrator",
	"Database Manager",
	"Daycare Director",
	"Decorator",
	"Deliverer",
	"Delivery Driver",
	"Delivery Technician",
	"Delivery assistant",
	"Dental Assistant",
	"Dental Hygienist",
	"Dental Prosthetist",
	"Dental Surgeon",
	"Dental Technician",
	"Department Manager",
	"Deployment Manager",
	"Depot Manager",
	"Deputy Director",
	"Deputy Director General",
	"Design Calculator",
	"Design Office Manager",
	"Design Office Technician",
	"Design technician",
	"Designer",
	"Designer Designer",
	"Designer Developer",
	"Designer Draughtsman",
	"Designer Editor",
	"Designer-Director",
	"Developer",
	"Developer Administrator",
	"Developer Architect",
	"Developer DOTNET",
	"Developer DRUPAL",
	"Developer FLASH",
	"Developer Integrator",
	"Developer JQUERY",
	"Developer LOTUS NOTES",
	"Developer MAGENTO",
	"Developer PRESTASHOP",
	"Developer Project Manager",
	"Developer SHAREPOINT",
	"Developer SYMFONY",
	"Developer VISUAL BASIC",
	"Development Advisor",
	"Development Director",
	"Development Expert",
	"Development Officer",
	"Development and Management Consultant",
	"Dietician",
	"Digital Brand Manager",
	"Digital Consultant",
	"Digital Manager",
	"Digital Marketing Manager",
	"Digital Multimedia Product Manager",
	"Digital Press Operator",
	"Digital Printing Technician",
	"Digital Strategy Consultant",
	"Digital Transformation Advisor...",
	"Digital Transformation Consultant",
	"Direct Marketing Manager",
	"Director",
	"Director of Accommodation",
	"Director of Human Resources",
	"Director of Operations",
	"Director of Social Establishment",
	"Director of a Design Office",
	"Diver",
	"Dock Agent",
	"Doctor",
	"Documentalist",
	"Documentary assistant",
	"Documentation Technician",
	"Dog Breeder",
	"Domestic help",
	"Drama teacher",
	"Driller",
	"Driver",
	"Driver Courier",
	"Driver Mechanic",
	"Driving instructor",
	"Dry cleaning employee",
	"Dyer",
	"Dyer Bleacher",
	"E-Category Manager",
	"E-Commerce Consultant",
	"E-Commerce Manager",
	"E-Commerce and Marketplace Consultant...",
	"E-Health Consultant",
	"E-Marketer",
	"E-Reputation Manager",
	"Early Childhood Educator",
	"Earthworks Manager...",
	"Ecologist",
	"Econome",
	"Economic Consultant",
	"Economic, Legal and Fiscal Consultant...",
	"Economist",
	"Editing Assistant",
	"Editor",
	"Editor-in-Chief",
	"Editorial Manager",
	"Editorial Secretary",
	"Education Advisor",
	"Education and Training Consultant",
	"Educational Director",
	"Educational assistant",
	"Educator",
	"Electrical Design Technician",
	"Electrical Designer",
	"Electrical Equipment Technician...",
	"Electrical Inspection Technician",
	"Electrical Maintenance Technician",
	"Electrical Maintenance Technician...",
	"Electrical Systems Installer",
	"Electrical Technician",
	"Electrical appliance repairer",
	"Electrical technician",
	"Electrician",
	"Electrician Cable Maker",
	"Electrician Fitter",
	"Electrician Installer",
	"Electromechanic",
	"Electromechanic Maintenance",
	"Electromechanical Maintenance Technician...",
	"Electromechanical technician",
	"Electronic Cable Fitter",
	"Electronic Maintenance Engineer",
	"Electronic Maintenance Technician",
	"Electronic Money Analyst",
	"Electronic Technician",
	"Electronic Test and Measurement Consultant...",
	"Electronic technician",
	"Electrotechnical Technician",
	"Emailing Manager",
	"Embedded Systems Developer",
	"Emergency doctor",
	"Employee Floor",
	"Energeticist",
	"Energy Efficiency Advisor",
	"Energy Project Manager",
	"Engineer",
	"Engraver",
	"Entrepreneurial Support Consultant...",
	"Entrepreneurship Consultant at the University of ...",
	"Entrepreneurship and Business Consultant...",
	"Environmental Consultant",
	"Environmental Officer",
	"Environmental Risk Consultant",
	"Environmental Studies Officer",
	"Environmental Technician",
	"Equine Veterinarian",
	"Equipment Installation Technician...",
	"Equipment Manager",
	"Equipment Technician",
	"Evaluation Advisor",
	"Evening host",
	"Event Manager",
	"Event Planner",
	"Executive Assistant",
	"Executive Director",
	"Executive Officer",
	"Executive Search Consultant",
	"Executive Secretary",
	"Executive Technical-Commercial Engineer",
	"Executive Treasurer",
	"Expatriation Consultant",
	"Expert Administrator",
	"Expert Consultant Bilan Carbone",
	"Expert Developer",
	"Expert Strategy Consultant",
	"Explorer",
	"Export Manager",
	"Export Sales",
	"Export Sales Assistant",
	"Export Sales Manager",
	"Export framework",
	"External Relations Officer",
	"External Sales Consultant",
	"FLEX Developer",
	"Facilities Technician",
	"Facility Manager",
	"Factor",
	"Family Assistance",
	"Family assistant",
	"Fashion Designer",
	"Fast food employee",
	"Fastsourcing Consultant",
	"Fibre Optic Technician",
	"Fiduciary",
	"Field Collection Officer",
	"Field Sales",
	"Filing Agent",
	"Film Director",
	"Finance Consultant",
	"Finance Risk and Compliance Consultant...",
	"Financial",
	"Financial Advisor",
	"Financial Analyst",
	"Financial Analyst and Manager",
	"Financial Auditor",
	"Financial Controller",
	"Financial Coordinator",
	"Financial Director",
	"Financial Framework",
	"Financial Management Consultant",
	"Financial Manager",
	"Financial Risk Consultant",
	"Financial Teleconsultant",
	"Finishing Agent",
	"Finishing Machine Operator",
	"Fire Extinguisher Technician...",
	"Fire Officer",
	"Firefighter",
	"Fisherman",
	"Fishmonger",
	"Fitness instructor",
	"Fitter",
	"Fitter and Trimmer",
	"Fleet Manager",
	"Flight Commander",
	"Flight Supervisor",
	"Flight attendant",
	"Florist",
	"Flow driver",
	"Fluid Technician",
	"Flyer Distributor",
	"Folding machine operator",
	"Food Industry Consultant...",
	"Food Industry Technician",
	"Food Laboratory Technician...",
	"Food Manufacturing Manager...",
	"Food Processing Machine Operator...",
	"Food Production Operator...",
	"Food and Beverage Manager",
	"Football Coach",
	"Football Educator",
	"Foreign Exchange Market Operator",
	"Foreign Language Teacher",
	"Foreman",
	"Forensic Expert",
	"Forestry Technician",
	"Forfaitist",
	"Forklift Electrician",
	"Forklift operator",
	"Formworker",
	"Foundry",
	"Framer",
	"Freelancer",
	"French teacher",
	"Front-Office Manager",
	"Fruit and Vegetable Department Manager",
	"Functional Analyst",
	"Functional Architect",
	"Functional Designer",
	"Functional Expert",
	"Functional Project Manager",
	"Functional Support",
	"Functional Tester",
	"Fundraiser",
	"Funeral Assistant",
	"Furniture Assembler",
	"Gallery Manager",
	"Game Designer",
	"Gardener",
	"Gardening Equipment Salesman",
	"Gatekeeper",
	"General Accountant",
	"General Coordinator",
	"General Counsel",
	"General Manager",
	"General Practitioner",
	"General Resources Director",
	"General Resources Manager",
	"General Services Manager",
	"General Services Officer",
	"General Supervisor",
	"Geographer",
	"Geologist",
	"Geomatician",
	"Geomatics Technician",
	"Geopolitical Consultant",
	"Geotechnician",
	"Gerontological Care Assistant",
	"Glacier",
	"Glass Industry Technician",
	"Glazier",
	"Glazier Mirror Maker",
	"Goldsmith in Silverware",
	"Governor Floor",
	"Governor General",
	"Graphic Designer Decorator",
	"Graphic Industries Technician",
	"Graphic designer",
	"Graphologist",
	"Groom",
	"Group Director",
	"Group Leader",
	"Group Management Consultant",
	"Guardian",
	"Guidance Counsellor",
	"Guide",
	"Gynaecologist",
	"Gynaecologist Obstetrician",
	"HR Administrative Support Officer",
	"HR Assistant",
	"HR Business Consultant",
	"HR Communication Consultant",
	"HR Consultant",
	"HR Coordinator",
	"HR Development Manager",
	"HR Development Officer",
	"HR Manager",
	"HSE Animator",
	"HSE Controller",
	"HSE Supervisor",
	"HSE Technician",
	"HTML Developer",
	"Hairdresser",
	"Hairdresser Visagist",
	"Harness Assembly Technician",
	"Head Machinist",
	"Head Mechanic",
	"Head Storekeeper",
	"Head of Advertising",
	"Head of Agency",
	"Head of Archives",
	"Head of Asset Management",
	"Head of Audit and Management Control...",
	"Head of Cabinet",
	"Head of Cardboard Printing Workshop",
	"Head of Career",
	"Head of Cashier",
	"Head of Chemicals Workshop",
	"Head of Chur",
	"Head of Construction",
	"Head of Daycare",
	"Head of Department",
	"Head of Dock",
	"Head of Education",
	"Head of Educational Services",
	"Head of Fire and Safety Services...",
	"Head of Food Processing Workshop",
	"Head of Green Spaces",
	"Head of Laboratory",
	"Head of Logistics",
	"Head of Maintenance",
	"Head of Manufacturing Workshop",
	"Head of Manufacturing in Printing",
	"Head of Mechanical Workshop",
	"Head of Metal Workshop",
	"Head of Mission",
	"Head of Mobile Strategy",
	"Head of Operations",
	"Head of Orchestra",
	"Head of Personnel",
	"Head of Research and Development...",
	"Head of Sales",
	"Head of Sales Administration...",
	"Head of Sector in GMS",
	"Head of Skills Unit",
	"Head of Studies",
	"Head of Technical Office",
	"Head of Treasury",
	"Head of Works",
	"Head of Workshop",
	"Head of Zone",
	"Head of rank",
	"Headhunter",
	"Headmaster",
	"Headmaster Nursery School",
	"Headmaster of a secondary school",
	"Health Benefits Manager",
	"Health Care Aide",
	"Health Consultant",
	"Health and Social Consultant",
	"Health executive",
	"Heating Maintenance Technician...",
	"Heating and air conditioning installer...",
	"Heating engineer",
	"Heating technician",
	"Help Desk Manager",
	"Help Desk Technician",
	"Help for the Elderly",
	"Help for the person",
	"Herbalist",
	"High Voltage Line Technician",
	"Highway Designer",
	"Hiking Guide",
	"Holiday Club Leader",
	"Home Care Nurse",
	"Home Help",
	"Home Salesman",
	"Horse Breeding Technician",
	"Horse trainer",
	"Horticulturist",
	"Horticulturist Nurseryman",
	"Hospital Cleaner",
	"Hospital Officer",
	"Hospital Service Officer",
	"Hospitality Consultant",
	"Hostess",
	"Hotel Manager",
	"Hotel Receptionist",
	"Hotliner",
	"Household appliance technician",
	"Household employee",
	"Housekeeper",
	"Human Resources Advisor",
	"Human Resources Consultant",
	"Human Resources Manager",
	"Hydraulic Cell Mechanic",
	"Hydraulic engineer",
	"Hydrotherapist",
	"Hygienist",
	"Hypermarket Manager",
	"ICT trainer",
	"IPHONE Developer",
	"IS Architect",
	"IS Security Manager",
	"IT Admin",
	"IT Architect",
	"IT Asset Manager",
	"IT Development Technician...",
	"IT Director",
	"IT Framework",
	"IT Manager",
	"IT Project Manager",
	"IT Security Coordinator",
	"IT Security Manager",
	"Illustrator",
	"Image Consultant",
	"Image Reporter",
	"Image and Sound Editor",
	"Immigration Consultant",
	"Import Buyer",
	"Import Export Agent",
	"Import Export Assistant",
	"Import Export Coordinator",
	"Import Export Manager",
	"Inbound Calls Telephonist",
	"Independent Manager",
	"Individual Coaching Consultant",
	"Industrial Buyer",
	"Industrial Ceramist",
	"Industrial Cleaning Operator",
	"Industrial Confectionery Technician...",
	"Industrial Control Technician",
	"Industrial Director",
	"Industrial Electrician",
	"Industrial Equipment Electrician",
	"Industrial Launderer",
	"Industrial Machine Operator",
	"Industrial Maintenance Manager",
	"Industrial Maintenance Operator...",
	"Industrial Maintenance Technician",
	"Industrial Management Consultant",
	"Industrial Management Consultant and...",
	"Industrial Manufacturing Agent",
	"Industrial Mechanic",
	"Industrial Pharmacist",
	"Industrial Pipefitter",
	"Industrial Project Manager",
	"Industrial Property Consultant",
	"Industrial Tools Salesman",
	"Industrial painter",
	"Industrialization technician",
	"Industry Workshop Manager",
	"Information System Planner IS",
	"Infrastructure Architect",
	"Injection Extrusion Plastics Operator...",
	"Injection Molding Machine Operator",
	"Innovation Consultant",
	"Inseminator",
	"Inside Sales Executive",
	"Institutional Relations Officer",
	"Instructor",
	"Instrumentalist",
	"Instrumentation Technician",
	"Insurance Accountant",
	"Insurance Actuarial Consultant",
	"Insurance Advisor",
	"Insurance Broker",
	"Insurance Consultant",
	"Insurance Customer Advisor",
	"Insurance Manager",
	"Insurance Manager Writer",
	"Insurance Sales Representative",
	"Insurance Sales Technician",
	"Insurance agent",
	"Insurance employee",
	"Insurance expert",
	"Insurance trainer",
	"Insurance underwriter",
	"Integration Advisor",
	"Integrator",
	"Intercultural Communication Consultant...",
	"Interior designer",
	"Internal Auditor",
	"Internal Communications Manager",
	"Internal Consultant",
	"Internal Control Risk Audit Consultant...",
	"International Business Consultant",
	"International Buyer",
	"International Consultant",
	"International Development Consultant...",
	"International Finance Consultant",
	"International Lawyer",
	"International Marketing Manager",
	"International Organisations Consultant...",
	"International Sales Manager",
	"Interpreter",
	"Investigation Officer",
	"Investigator",
	"Investment Banking Consultant",
	"Investment Consultant in Real Estate...",
	"Ironmonger",
	"Ironworker",
	"Itinerant Salesman",
	"J2EE Developer",
	"JAVA Developer",
	"JOOMLA Developer",
	"Jeweller",
	"Jewellery setter",
	"Job placement advisor",
	"Journalist",
	"Journalist Editor",
	"Juggler",
	"Key Account Manager",
	"Kitchen clerk",
	"Kitchen designer",
	"Kitchen technician",
	"Knowledge Management Consultant...",
	"LINUX Developer",
	"LV delivery driver",
	"Laboratory Manager",
	"Laboratory Officer",
	"Laboratory Technician",
	"Laboratory Technician Industry",
	"Laboratory assistant",
	"Laboratory technician for analysis...",
	"Laboratory technician for the control of...",
	"Lacquerer",
	"Laminator",
	"Laminator Moulder",
	"Land Surveyor",
	"Land Technician",
	"Landscape Architect",
	"Landscape Designer",
	"Landscape Technician",
	"Landscape Work Supervisor",
	"Landscape gardener",
	"Landscaper",
	"Large-scale farmer",
	"Laser Printer Copier Technician",
	"Laundry Agent",
	"Lawyer",
	"Layout artist",
	"Lead Pharmacist",
	"Lean Management Consultant",
	"Lean Manufacturing Manager",
	"Lean Quality Safety Consultant",
	"Lean Six Sigma Consultant",
	"Leather Cutter",
	"Leatherworker",
	"Led Panel Technician",
	"Legal Advisor",
	"Legal Assistant",
	"Legal Consultant",
	"Legal Counsel",
	"Legal Officer",
	"Legal Secretary",
	"Legal and Tax Consultant",
	"Leisure Centre Director",
	"Leisure time coordinator",
	"Liaison Officer",
	"Librarian",
	"Library Curator",
	"Life Insurance Actuarial Consultant...",
	"Life actuary",
	"Lifeguard",
	"Lift fitter",
	"Lift operator",
	"Lift technician",
	"Lighting Technician",
	"Lighting designer",
	"Line Manager",
	"Line driver",
	"Lingerie Agent",
	"Linguist",
	"Liquidation Consultant",
	"Litigation Lawyer",
	"Litigation Manager",
	"Litigation and Forensic Consultant",
	"Livestock Technician",
	"Load Optimisation Consultant...",
	"Loader driver",
	"Local Development Advisor",
	"Local technician",
	"Locksmith",
	"Locksmith Coordinator",
	"Logistician",
	"Logistics Assistant",
	"Logistics Consultant",
	"Logistics Coordinator",
	"Logistics Director",
	"Logistics Manager",
	"Logistics Officer",
	"Logistics Operator",
	"Logistics Procurement Consultant...",
	"Logistics Technician",
	"Logistics and Storage Manager",
	"Loss Prevention Advisor",
	"Low Voltage Technician",
	"Luxury Goods Seller",
	"Luxury Salesman",
	"Machine Operator",
	"Machine Setter",
	"Machine Setting Operator",
	"Machine Tool Maintenance Technician...",
	"Machine Tool Operator, Ordered by...",
	"Machine Tool Setter",
	"Machinery Mechanic",
	"Machinery Operator",
	"Machining Technician",
	"Machinist",
	"Mail Handler",
	"Maintenance Electrician",
	"Maintenance Manager",
	"Maintenance Mechanic",
	"Maintenance Methods Technician",
	"Maintenance Officer",
	"Maintenance Officer Nature",
	"Maintenance Operator",
	"Maintenance Support Engineer",
	"Maintenance Team Leader",
	"Maintenance Technician",
	"Maintenance Technician for Construction Equipment...",
	"Maître d'Hôtel",
	"Make-up artist",
	"Management Assistant",
	"Management Consultant",
	"Management Consultant Specialist in the...",
	"Management Control Director",
	"Management Controller",
	"Manager",
	"Manager Operations",
	"Manager Retail Innovation",
	"Manager Service Desk",
	"Manager of a dry cleaner",
	"Managing Director",
	"Maneuver",
	"Manicure",
	"Manufacturing Agent",
	"Manufacturing Manager",
	"Manufacturing Manager Industry",
	"Manufacturing Manager Industry...",
	"Manufacturing Operator",
	"Manufacturing Technician",
	"Manufacturing Technician Industry...",
	"Mapping Technician",
	"Marin",
	"Marine Operations Officer",
	"Marine consignee",
	"Maritime Expert",
	"Marker",
	"Market Operator Trader",
	"Market Risk Management Consultant...",
	"Market gardener",
	"Market gardening Horticulture worker",
	"Marketing Analyst",
	"Marketing Assistant",
	"Marketing Campaign Manager",
	"Marketing Communication Consultant...",
	"Marketing Consultant",
	"Marketing Director",
	"Marketing Manager",
	"Marketing Project Manager",
	"Marketing Research Officer",
	"Marketing and Communication Manager...",
	"Marketing and Management Consultant...",
	"Marketplace Manager",
	"Marriage and Family Counsellor",
	"Martial Arts Coach",
	"Mason",
	"Master Dog",
	"Master Reimburser",
	"Master driver",
	"Material Handling Worker",
	"Material handler",
	"Material handler forklift operator",
	"Mathematician Computer scientist",
	"Mathematics teacher",
	"Measurement and Control Technician",
	"Measurer",
	"Mechanic",
	"Mechanic for Lifting and Construction Machinery...",
	"Mechanical Design Technician",
	"Mechanical Designer",
	"Mechanical Inspector",
	"Mechanical Maintenance Technician",
	"Mechanical Manufacturing Technician",
	"Mechanical Technician",
	"Mechanical Testing Technician",
	"Mechanical fitter",
	"Media Planner",
	"Media Reporter",
	"Media Research Officer",
	"Mediatheque",
	"Mediation Consultant",
	"Medical Advisor Hospital",
	"Medical Assistant",
	"Medical Biologist",
	"Medical Delegate",
	"Medical Equipment Installer",
	"Medical Secretary",
	"Medical Specialist",
	"Medical Technician",
	"Medical Visitor",
	"Medical and psychological assistant",
	"Membership Consultant",
	"Merchandiser",
	"Merchandising Manager",
	"Merchant Navy Mechanic",
	"Merchant Navy Officer",
	"Mergers and acquisitions strategy consultant...",
	"Metal Builder",
	"Metal Builder's Helper",
	"Metal carpenter",
	"Metallurgy Technician",
	"Meteorologist",
	"Methods Technician",
	"Metrologist",
	"Metrologist Technician",
	"Microsoft Expert",
	"Middle Office Manager",
	"Midwife",
	"Miller",
	"Milling Technician",
	"Milling machine",
	"Mining",
	"Mining Site Manager",
	"Mobile Developer",
	"Mobile Hotliner",
	"Mobile Maintenance Technician",
	"Mobility Consultant",
	"Modeller",
	"Moderator Social Networking Forum",
	"Monitor",
	"Monitor Educator",
	"Motion Designer",
	"Motor Insurance Expert",
	"Mould and Injection Machine Setter...",
	"Mould maker",
	"Mouldmaker",
	"Mountain Guide",
	"Multi-purpose agent",
	"Multi-skilled operator",
	"Multi-skilled secretary",
	"Multi-skilled technician",
	"Multi-skilled worker",
	"Multimedia Advisor",
	"Multimedia Communication Consultant",
	"Multimedia Developer",
	"Multimedia Electronics Technician",
	"Multimedia Graphic Designer",
	"Multimedia Producer",
	"Multimedia Project Manager",
	"Multimedia Technician",
	"Multipurpose Assistant",
	"Museum Director",
	"Museum Guide",
	"Museum curator",
	"Music Education Teacher",
	"Music teacher",
	"Musical Instruments Salesman",
	"Musician",
	"Musician Intervenor",
	"NET Developer",
	"NTIC Communication Consultant",
	"National Councillor",
	"Natural Areas Maintenance Officer",
	"Naval Industrial Mechanic",
	"Negotiator",
	"Network Administrator",
	"Network Analyst",
	"Network Architect",
	"Network Coordinator",
	"Network Director",
	"Network Infrastructure Expert",
	"Network Project Manager",
	"Network Security Architect",
	"Network Systems Technician",
	"Network Technician",
	"Networks Expert",
	"New Markets Development Consultant...",
	"Night Supervisor",
	"Night Watchman",
	"Non-Life Actuary",
	"Notary",
	"Notary Clerk",
	"Numerical Control Machine Operator...",
	"Numerical Control Operator",
	"Nurse Anaesthesia Intensive Care Unit",
	"Nurse Executive",
	"Nursery nurse",
	"Nurseryman",
	"Nutrition Consultant",
	"Nutritionist",
	"ORACLE Developer",
	"Occupational Health and Safety Consultant...",
	"Occupational Psychologist",
	"Occupational Risk Consultant",
	"Occupational Therapist",
	"Occupational physician",
	"Office Agent",
	"Office Assistant",
	"Office Consultant",
	"Office Manager",
	"Offset Machine Operator",
	"Offset Printing Machine Operator...",
	"Oncologist",
	"Online Advertising Consultant",
	"Operating Room Nurse",
	"Operating agent in a waste sorting centre...",
	"Operational Activity Manager",
	"Operational Consultant",
	"Operational Marketing Consultant",
	"Operational Marketing Manager",
	"Operational Monitoring Officer",
	"Operations Analyst",
	"Operations Integrator",
	"Operations Manager",
	"Operations Officer",
	"Operations Technician",
	"Operations and Support Consultant",
	"Operator",
	"Operator Agency",
	"Operator Setter",
	"Operator on Special Purpose Machines...",
	"Ophthalmologist",
	"Optical Technician",
	"Optician",
	"Optometrist",
	"Order Picker",
	"Organic farmer",
	"Organisational Consultant",
	"Orthodontist",
	"Orthoprosthetist",
	"Orthoptist",
	"Osteopath",
	"Outplacement Consultant",
	"PHP Developer",
	"PVC carpenter",
	"Packager Integrator",
	"Packaging Operator",
	"Paramedical",
	"Parameterizer",
	"Parking Operations Officer",
	"Partner Relations Manager...",
	"Partnership Manager",
	"Passenger Traffic Controller",
	"Passive Construction Consultant",
	"Pastry Clerk",
	"Pastry chef",
	"Payroll Assistant",
	"Payroll Manager",
	"Payroll Technician",
	"Payroll and Administrative Manager",
	"Payroll and Billing Secretary",
	"Pedagogical Advisor",
	"Pedagogical Guidance Counsellor",
	"Pediatrician",
	"Pedologist",
	"Pension Insurance Managers...",
	"People and Change Consultant",
	"Personnel Administration Consultant...",
	"Personnel Administration Manager...",
	"Pest Control Officer",
	"PhD student",
	"Pharmaceutical Production Technician",
	"Pharmaceutical Research Officer",
	"Pharmacist",
	"Pharmacist Regulatory Affairs",
	"Pharmacist's assistant",
	"Pharmacy Preparer",
	"Phoning Agent",
	"Photo Developer",
	"Photo retoucher",
	"Photocopier Technician",
	"Photographer",
	"Photoshop designer",
	"Photovoltaic installer",
	"Physical and Sports Education teacher...",
	"Physical trainer",
	"Physician Biologist",
	"Physicist",
	"Physiotherapist",
	"Pipefitter",
	"Pizzaiolo",
	"Planner",
	"Planning Manager",
	"Planning Officer",
	"Planning and Scheduling Officer...",
	"Plant Manager",
	"Plant Quality Controller",
	"Plant Quality Manager",
	"Plasterer",
	"Plastic Art Teacher",
	"Plastic Injection Machine Operator...",
	"Plastic moulder",
	"Plastics Processing Line Operator",
	"Plastics fitter",
	"Platform Manager",
	"Playground Manager",
	"Playroom Manager",
	"Plumber",
	"Plumber Boiler fitter",
	"Plumber Technician",
	"Plumbing and Sanitary Installer",
	"Point of Sale Manager",
	"Police officer",
	"Policy Officer",
	"Polisher",
	"Political Science Consultant",
	"Pompist",
	"Pontier",
	"Port Officer",
	"Port agent",
	"Portfolio Manager",
	"Pottery Technician",
	"Poultry Technician",
	"Powerline Fitter",
	"Pre-Sales",
	"Pre-Sales Animator",
	"Pre-Sales Consultant",
	"Pre-Sales Technician",
	"Preparer",
	"Preparer in the food industry...",
	"Press Officer",
	"Press Relations Officer",
	"Press setter",
	"Pressier",
	"Prevention and Mediation Officer",
	"Pricing Supervisor",
	"Primary Teacher",
	"Principal Business Consultant",
	"Printer",
	"Printing Machine Operator",
	"Private Banking Consultant...",
	"Private driver",
	"Procurement Manager",
	"Procurement and Sourcing Consultant",
	"Product Consultant",
	"Product Designer",
	"Product Manager",
	"Product Manager Assistant",
	"Product Manager Pharmaceutical Industry...",
	"Product Manager Prices",
	"Product Marketing Manager",
	"Product and Market Innovation Consultant...",
	"Production Agent",
	"Production Assistant",
	"Production Flow Manager",
	"Production Line Manager",
	"Production Line Operator...",
	"Production Machine Operator...",
	"Production Machinery Mechanic",
	"Production Manager",
	"Production Operator",
	"Production Pharmacist",
	"Production Supervisor",
	"Production Team Leader",
	"Production Technician",
	"Production Technician for the...",
	"Production Workshop Manager",
	"Production worker",
	"Professional Coach",
	"Professional Development Coach or...",
	"Professional Public Trainer",
	"Professor Art",
	"Professor Economics",
	"Professor of History and Geography",
	"Professor of Life and Environmental...",
	"Professor of Philosophy",
	"Professor of Physics and Chemistry",
	"Profit Centre Manager",
	"Programmer",
	"Programming Officer",
	"Project Control Manager",
	"Project Coordinator",
	"Project Director",
	"Project Leader",
	"Project Management Consultant",
	"Project Management Consultant...",
	"Project Management Manager",
	"Project Manager",
	"Project Manager AMO",
	"Project Manager Ecologist",
	"Project Manager Polluted Sites and Soils",
	"Project Manager Systems Architect",
	"Promotion Officer",
	"Proofreader",
	"Property Consultant",
	"Property Manager",
	"Prosthetist",
	"Prosthetist Ceramist",
	"Psychoanalyst",
	"Psychological guidance counsellor...",
	"Psychologist",
	"Psychotherapist",
	"Public Finance Consultant",
	"Public Health Consultant",
	"Public Place Valet",
	"Public Procurement Consultant",
	"Public Procurement Manager",
	"Public Relations Consultant",
	"Public Relations Manager",
	"Public Relations Officer",
	"Public Sector Consultant",
	"Public Transport Driver",
	"Public Writer",
	"Publisher",
	"Purchaser",
	"Purchasing Application Support Agent",
	"Purchasing Consultant",
	"Purchasing Director",
	"Purchasing Manager",
	"Purchasing Officer",
	"Purchasing and Supply Assistant...",
	"Purchasing and Supply Manager",
	"QHSE Manager",
	"Qualitician",
	"Quality Assistant",
	"Quality Assurance Manager",
	"Quality Assurance Pharmacist",
	"Quality Auditor",
	"Quality Control Manager",
	"Quality Control Manager...",
	"Quality Control Technician",
	"Quality Control Technician Industry...",
	"Quality Control Technician...",
	"Quality Manager",
	"Quality Project Manager",
	"Quality Supervisor",
	"Quality Technician",
	"Quality and Process Manager",
	"Quality controller",
	"Quality coordinator",
	"Quantity surveyor",
	"Radiation Protection Technician",
	"Radiation protectionist",
	"Radio Reporter",
	"Radio Technician",
	"Radio and TV journalist",
	"Radio host",
	"Radiologist",
	"Radiology Manipulator",
	"Rail Navigator",
	"Real Estate Advisor",
	"Real Estate Agency Director",
	"Real Estate Agent",
	"Real Estate Consultant Offices",
	"Real Estate Expert",
	"Real Estate Lawyer",
	"Real Estate Negotiator",
	"Real Estate Operations Manager",
	"Real Estate Project Manager",
	"Real Estate Prospector",
	"Real Estate Sales Advisor",
	"Real Estate Sales Manager",
	"Real Estate and Hotel Consultant",
	"Receiver",
	"Receptionist",
	"Recruitment Assistant",
	"Recruitment Consultant",
	"Recruitment Consultant Temporary Work...",
	"Recruitment Manager",
	"Recruitment Officer",
	"Recruitment and Mobility Advisor",
	"Referrer",
	"Refrigeration Technician",
	"Refrigeration and air conditioning technician",
	"Refrigeration fitter",
	"Refrigeration specialist",
	"Regional Director",
	"Regional Manager",
	"Regional Sales Manager",
	"Regulatory Affairs Assistant",
	"Regulatory Affairs Manager",
	"Rehabilitator",
	"Reinforced Concrete Draughtsman",
	"Reinsurance Accountant",
	"Relocation Consultant",
	"Relocation Officer",
	"Renewable Energy and Energy Efficiency...",
	"Rental Manager",
	"Reporter",
	"Reporting Officer",
	"Reporting and Consolidation Consultant...",
	"Representative",
	"Research Fellow in Economics of the Economy...",
	"Research Laboratory Technician",
	"Research Laboratory Technician for the...",
	"Research Officer",
	"Research Professor of Medicine",
	"Research Teacher in Physical Sciences...",
	"Research Technician",
	"Research and Development Officer",
	"Research and Development Technician...",
	"Researcher",
	"Researcher in Exact Sciences",
	"Researcher in Humanities or Social Sciences...",
	"Resource Manager",
	"Respiratory Therapist",
	"Responsible debtor",
	"Restaurant Manager",
	"Restaurant Service Agent...",
	"Restorer",
	"Restructuring Consultant",
	"Retailer",
	"Retention in Employment Consultant",
	"Retirement Consultant",
	"Retoucher",
	"Revenue Manager",
	"Revenue Officer",
	"Risk Analyst",
	"Risk Management Consultant",
	"Risk Manager",
	"Risk Prevention Consultant",
	"Road Freight Driver",
	"Road Passenger Driver",
	"Robot Mechanic",
	"Robotics Technician",
	"Roofer",
	"Roofer Bardeur",
	"Rural Development Consultant",
	"Rural Tourism Consultant",
	"SAP Consultant",
	"SAP Developer",
	"SEO Consultant",
	"SEO SEM Manager",
	"SEO specialist",
	"SME Consultant",
	"SPL Driver",
	"SPL driver",
	"SQL Developer",
	"Safety Controller",
	"Safety Coordinator",
	"Sailing Instructor",
	"Sailor",
	"Sales Administration Assistant",
	"Sales Administrator",
	"Sales Advisor",
	"Sales Animator",
	"Sales Assistant",
	"Sales Consultant in Information Technology...",
	"Sales Coordinator",
	"Sales Executive",
	"Sales Inspector",
	"Sales Management Consultant",
	"Sales Manager",
	"Sales Performance Consultant...",
	"Sales Promotion Officer",
	"Sales Representative",
	"Sales Team Manager",
	"Sales Technician",
	"Sales and Marketing Consultant",
	"Sales assistant",
	"Sales consultant",
	"Sales consultant for spare parts",
	"Sales promoter",
	"Salesforce Consultant",
	"Salesman",
	"Salesman Appliances",
	"Salesman DIY Tools",
	"Salesman Equipped Kitchen",
	"Salesman General Food",
	"Salesman in Personal Equipment",
	"Sanitary Fitter",
	"Sanitation Officer",
	"Saucier cook",
	"Sawmill Technician",
	"Sawyer",
	"Scaffolder",
	"Scaffolding fitter",
	"Scheduling Technician",
	"Scheduling and Launch Manager",
	"Scheduling and Launching Technician",
	"Scheduling and Planning Manager...",
	"School Director",
	"Scientific Editor",
	"Scrapper",
	"Screen printer",
	"Script Editor",
	"Sculptor",
	"Search Engine Optimisation Officer",
	"Seasonal Agricultural Helper",
	"Secretary",
	"Secretary General",
	"Secretary Receptionist",
	"Secretary Switchboard operator",
	"Security Architect",
	"Security Expert",
	"Security Manager",
	"Security Officer",
	"Security Systems Technician",
	"Security and Surveillance Officer",
	"Sedentary Sales Technician",
	"Sedentary Salesperson",
	"Self-service employee",
	"Seller Goods Equipment",
	"Seller Sporting Goods",
	"Semi-Automatic Welder",
	"Senior Manager",
	"Server",
	"Service Coordinator",
	"Service Station Employee",
	"Service Station Manager",
	"Service technician",
	"Sewing Machine Mechanic",
	"Sewing Machine Operator",
	"Sewing Machine Setter",
	"Sheet metal worker",
	"Shelf manager",
	"Ship's Captain",
	"Shoemaker",
	"Shop Manager",
	"Shop Salesperson",
	"Show host",
	"Showroom Manager",
	"Silo driver",
	"Singer",
	"Site Director",
	"Site Electrician",
	"Site Manager",
	"Site Technician",
	"Skilled Worker",
	"Skyguide",
	"Social Coordinator",
	"Social Law Lawyer",
	"Social Mediation Officer",
	"Social Mediator",
	"Social Network Consultant",
	"Social Protection Consultant",
	"Social Relations Manager",
	"Social Service Assistant",
	"Social worker",
	"Socio-Cultural Animator",
	"Socio-professional Integration Officer...",
	"Sociologist",
	"Software Architect",
	"Software Developer",
	"Software Integrator",
	"Sommelier",
	"Sorting Agent",
	"Sound Assistant",
	"Sound Mixer",
	"Sound technician",
	"Sourcing Manager",
	"Sous-Chef de Cuisine",
	"Speaker",
	"Special Educator",
	"Specialised Teacher",
	"Specialised Technical Educator",
	"Specialised Technician",
	"Specialist DIY Salesman",
	"Specialty Store Salesperson",
	"Speech therapist",
	"Sponsorship Officer",
	"Sports Activities Advisor",
	"Sports Animator",
	"Sports Coach",
	"Sports Educator",
	"Sports Hall Manager",
	"Sports Infrastructure Manager...",
	"Sports Instructor",
	"Sports Journalist",
	"Sports Teacher",
	"Sports and Leisure Advisor",
	"Spray painter",
	"Staff Consultant",
	"Stage Manager",
	"Stainless steel welder",
	"Stakeholder",
	"Stand Moderator",
	"State Registered Nurse",
	"Statistical Officer",
	"Statutory Auditor",
	"Statutory Management Consultant",
	"Steel Construction Team Leader...",
	"Steel Construction Technician",
	"Steel Construction Worker",
	"Sterilisation Officer",
	"Sterilisation Technician",
	"Steward",
	"Stock Manager",
	"Stockbroker",
	"Stone Sculptor",
	"Storage Facility Operator...",
	"Storage expert",
	"Storekeeper",
	"Storytelling Consultant",
	"Strategic Intelligence Officer",
	"Strategic Marketing Consultant",
	"Strategic Marketing Manager",
	"Strategic Planner",
	"Strategic Watchdog",
	"Strategy Consultant",
	"Strategy and Operations Consultant",
	"Strategy and Transactions Consultant...",
	"Stress Management Consultant",
	"Stretcher Bearer",
	"Structural engineering technician",
	"Structured Wiring Technician",
	"Subscriber Relations Trainer",
	"Supermarket Manager",
	"Supervision Consultant",
	"Supervisor",
	"Supervisory Technician",
	"Supply Chain Director",
	"Supply Chain Functional Consultant",
	"Supply Chain Planner",
	"Supply Planner",
	"Support Administrator",
	"Support Coordinator",
	"Support Technician",
	"Surface technician",
	"Surgeon",
	"Surveillance Camera Operator",
	"Surveillance and Security Manager",
	"Surveyor",
	"Surveyors Satisfaction Survey",
	"Sweeper",
	"Swimming Instructor",
	"Swimming pool specialist",
	"Swimming pool technician",
	"Switchboard operator",
	"System Administrator",
	"System Architect",
	"System Quality Assurance Pharmacist",
	"Systems Expert",
	"Systems Infrastructure Expert",
	"Systems Integrator",
	"Systems Project Manager",
	"Systems Technician",
	"TV director",
	"Tailor",
	"Talent Acquisition Consultant",
	"Talent Management Consultant",
	"Tannery Consultant",
	"Tax Consultant",
	"Tax specialist",
	"Taxi Driver",
	"Teacher",
	"Teacher College and High School",
	"Teacher Researcher",
	"Teaching Assistant",
	"Team Leader",
	"Team Leader, Facilities Maintenance",
	"Team Management Consultant",
	"Team Manager",
	"Technical Administrator",
	"Technical Advisor",
	"Technical Affairs Consultant",
	"Technical Affairs Officer",
	"Technical Analyst",
	"Technical Architect",
	"Technical Assistant",
	"Technical Coordinator",
	"Technical Customer Assistant",
	"Technical Designer",
	"Technical Director",
	"Technical Documentation Editor",
	"Technical Expert",
	"Technical Framework",
	"Technical Integrator",
	"Technical Manager",
	"Technical Officer",
	"Technical Operator",
	"Technical Project Manager",
	"Technical Referent",
	"Technical Sales Advisor",
	"Technical Sales Agent",
	"Technical Sales Consultant",
	"Technical Salesman Wood",
	"Technical Secretary",
	"Technical Services Manager",
	"Technical Studies Officer",
	"Technical Support",
	"Technical Support Agent",
	"Technical Support Consultant",
	"Technical Support Technician",
	"Technical Tester",
	"Technical Trainer",
	"Technical Translator",
	"Technical Writer",
	"Technical salesman for construction",
	"Technical tele-assistant",
	"Technical-Functional",
	"Technician",
	"Technician Installer Systems...",
	"Technician Operator Setter",
	"Technician in Business Management...",
	"Technician in Social and Health Intervention...",
	"Technology Transfer Consultant...",
	"Technology teacher",
	"Technology watchdog",
	"Tele-assistant",
	"Tele-investigator",
	"Telecom Project Manager",
	"Telemarketer",
	"Telemarketing Agent",
	"Telemarketing Agent at Home",
	"Teleoperator",
	"Telephone Advisor",
	"Telephonist",
	"Telephony Salesperson",
	"Teleprospector",
	"Telesecretary",
	"Television presenter",
	"Tender Consultant",
	"Tennis Instructor",
	"Test Analyst",
	"Test Architect",
	"Test Integrator",
	"Test Manager",
	"Test Technician",
	"Test Tools Expert",
	"Tester Receiver",
	"Textile Cleaner",
	"Textile Maintenance Technician...",
	"Textile Product Manager",
	"Textile Spinning Machine Operator...",
	"Textile Technician",
	"Thermal engineer",
	"Thermal technician",
	"Ticket agent",
	"Ticketing Agent",
	"Tig Arc welder",
	"Tig welder",
	"Tiler",
	"Time Management Consultant",
	"Time and Attendance Officer",
	"Tool and Die Maker",
	"Tooling Technician",
	"Toolmaker",
	"Tools Salesman",
	"Topographer",
	"Topographic Surveyor",
	"Topographic Technician",
	"Tour Guide",
	"Touring Coach Driver",
	"Tourism Agent",
	"Tourism Animator",
	"Tourism Consultant",
	"Tourism Promotion Manager",
	"Tourist Guide",
	"Tourist Reception Agent",
	"Toy seller",
	"Trade Marketing Manager",
	"Trader",
	"Traditional Network Vendor",
	"Traffic Manager",
	"Traffic Officer",
	"Train Traffic Technician",
	"Trainer",
	"Trainer Facilitator",
	"Trainer in Fashion Design",
	"Training Assistant",
	"Training Centre Consultant",
	"Training Centre Director",
	"Training Coordinator",
	"Training Director",
	"Training Manager",
	"Training and Documentation Consultant...",
	"Trainman",
	"Tramway driver",
	"Transactional Consultant in the...",
	"Transformation Consultant",
	"Transit Agent",
	"Transit Manager",
	"Transition Manager",
	"Translator",
	"Transport Manager",
	"Transport Operations Officer",
	"Transport Operations Technician",
	"Transport Planning Officer",
	"Transport Technician",
	"Travel Advisor",
	"Travel Agency Manager",
	"Travel Agent",
	"Travel Consultant",
	"Treasurer",
	"Treasury Consultant",
	"Treasury Officer",
	"Trimmer",
	"Trimmer Fitter",
	"Truck Driver",
	"Truck Mechanic",
	"Truck Technician",
	"Truck driver",
	"Truquist Editor",
	"Tuner",
	"Turner",
	"Turning and milling machine",
	"University Professor",
	"Upholsterer Saddler",
	"Urban planner",
	"User Support",
	"VB6 Developer",
	"VBA Developer",
	"Valet de Chambre",
	"Valet parking",
	"Vehicle Registration Agent",
	"Vendor Distributor",
	"Vendor Supplies",
	"Ventilation Technician",
	"Veterinarian",
	"Veterinary Assistant",
	"Veterinary Delegate",
	"Veterinary Technician",
	"Video Editor",
	"Video Surveillance Technician",
	"Vigil",
	"Virtual Reality Consultant",
	"Visual Merchandiser",
	"WINDEV Developer",
	"WORDPRESS Developer",
	"Waiter in Restaurant",
	"Warehouse Assistant",
	"Warehouse Operator",
	"Waste Treatment Consultant",
	"Waste Treatment Technician",
	"Watchmaker",
	"Water Analysis Laboratory Technician...",
	"Water Management Consultant",
	"Water Quality Technician",
	"Water Treatment Officer",
	"Water Treatment Technician",
	"Watercourse Maintenance Officer",
	"Wealth Management Advisor",
	"Wealth Management Consultant",
	"Weather Technician",
	"Weaver",
	"Weaving Technician",
	"Web Content Manager",
	"Web Developer",
	"Web Editor",
	"Web Product Manager",
	"Web Project Manager",
	"Web Sales Manager",
	"Web designer",
	"Web journalist",
	"Webdesigner",
	"Webmarketer",
	"Webmaster",
	"Website Administrator",
	"Website Moderator",
	"Welder",
	"Wholesale",
	"Wind Turbine Maintenance Technician",
	"Window cleaner",
	"Windows Expert",
	"Wiring Technician",
	"Wood Finisher",
	"Wood Varnisher",
	"Wood carpenter",
	"Wood painter",
	"Worker",
	"Works Controller",
	"Works Director",
	"Works Manager",
	"Works Technician",
	"Workshop Manager",
	"Workstation Architect",
	"Workstation Project Manager",
	"Writer",
	"Yield Management Consultant",
	"ZEND Developer",
}
